---
# Role tasks

- block:
    - name: Load user info from gitlab server
      command: >-
        gitlab
        {{ gitlab_fork_config_file_option }}
        {{ gitlab_fork_section_option }}
        -o yaml current-user get
      changed_when: false
      register: gitlab_fork_user_result

    - name: Load projects info from gitlab server
      command: >-
        gitlab
        {{ gitlab_fork_config_file_option }}
        {{ gitlab_fork_section_option }}
        -o yaml project list --all --owned true
      changed_when: false
      register: gitlab_fork_get_user_projects_result

    - name: Fork project in gitlab server
      shell: >-
        gitlab
        {{ gitlab_fork_config_file_option }}
        {{ gitlab_fork_section_option }}
        -o yaml
        project-fork create --project-id {{ gitlab_fork_target_project }}
      when:
        gitlab_fork_allow_duplicated
        or (not gitlab_fork_allow_duplicated and not gitlab_fork_is_duplicated)
      changed_when: gitlab_fork_result.stdout_lines | length > 0
      failed_when: gitlab_fork_result.rc != 0
      register: gitlab_fork_result

    - name: Setup fact with gitlab project fork info
      set_fact:
        gitlab_fork_fact: >-
          {{ (not gitlab_fork_result is skipped)
             | ternary(gitlab_fork_result.stdout | default("") | from_yaml,
                       gitlab_fork_search | first) }}
  vars:
    gitlab_fork_user: >-
      {{ gitlab_fork_user_result.stdout | from_yaml }}

    gitlab_fork_project_forks: >-
      {{ gitlab_fork_get_user_projects_result.stdout
         | from_yaml
         | selectattr("forked_from_project", "defined")
         | rejectattr("forked_from_project", "equalto", none)
         | list }}

    gitlab_fork_search: >-
      {{ gitlab_fork_project_forks
         | selectattr("forked_from_project.path_with_namespace",
                      "equalto",
                      gitlab_fork_project_path)
         | list }}

    gitlab_fork_is_duplicated: "{{ gitlab_fork_search | length != 0 }}"
  tags:
    - role::gitlab_fork
